# Generated by Django 4.2.4 on 2023-08-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="creat_at",
            new_name="create_at",
        ),
    ]
