# Generated by Django 4.2.4 on 2023-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_rename_creat_at_post_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="공개여부"),
        ),
    ]
