# Generated by Django 4.2.4 on 2023-08-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_post_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
