# Generated by Django 4.2.6 on 2023-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocab",
            name="word_no",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
